### ISSUE TITLE
How-To on Getting started

### ISSUE THREAD

**Issue by lukasstreit** [singer-io/tap-google-ads#46]
Hi all,

thank you very much for tackling this - Very much appreciated and we would very happily employ and possibly contribute to this project.

Getting started with the setup using meltano with this tap currently seems a bit daunting due to us not being able to locate a README with information on setup and parameters required to get this to work. It would be great if someone could add a few lines of How-To for laypersons trying to integrate this tool.

Best
Lukas

**Comment by gary-beautypie** [comment]
If it helps, example `meltano.yml`:
```
version: 1
send_anonymous_usage_stats: true
project_id: <project id>
plugins:
  extractors:
  - name: tap-google-ads
    namespace: tap_google_ads
    pip_url: git+https://github.com/singer-io/tap-google-ads.git
    executable: tap-google-ads
    capabilities:
    - state
    - catalog
    - discover
    config:
      customer_ids: <customer_ids>
      start_date: '2016-12-01T00:00:00Z'
      developer_token: <developer token>
      oauth_client_id: <client id>
      oauth_client_secret: <client secret>
      refresh_token: <refresh token>
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
```
